In [3]:
from bs4 import BeautifulSoup
import selenium
from selenium.common.exceptions import TimeoutException
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException, WebDriverException
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import requests
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
import requests

In [4]:
driver = webdriver.Chrome()

In [5]:
driver.get('https://rentberry.com/au/apartments/s/perth-wa-australia')
time.sleep(2)

In [6]:
consent = driver.find_element(By.XPATH, '/html/body/div[2]/div/div/div/div[2]/button[3]')
consent.click()

In [7]:
Rent_url = []
start = 0
end = 15
for page in range (start,end):
    url = driver.find_elements(By.XPATH,'//a[@class="property-card-bottom-address__text link-ghost font-xs one-line-string"]')
    for i in url:
        Rent_url.append(i.get_attribute('href'))
    
    Next_button = driver.find_elements(By.XPATH, '//span[@class="pagination-arrow-next"]')
    time.sleep(3)

In [8]:
print(len(Rent_url))

330

In [9]:
Bed = []
Bath = []
Area = []
Price = []
Pets = []
Address =[]
Deposit = []
AC  = []
Dishwasher = []
Storage = []

In [10]:
for url in Rent_url:
    driver.get(url)
    delay = 3
    
    try:
        bed = driver.find_element(By.XPATH, '//*[@id="main-info"]/rb-apartment-card-swiper/div/div[3]/rb-apartment-internals/section/div[1]/div[2]/span[1]')
        Bed.append(bed.text)
    except NoSuchElementException:
        Bed.append('Null')
    except StaleElementReferenceException:
        Bed.append('Null')
    except WebDriverException:
        Bed.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    try:
        bath = driver.find_element(By.XPATH, '//span[@class="bathrooms"]')
        Bath.append(bath.text)
    except NoSuchElementException:
        Bath.append('Null')
    except StaleElementReferenceException:
        Bath.append('Null')
    except WebDriverException:
        Bath.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    try:
        area = driver.find_element(By.XPATH, '//div[@class="internals-item"][3]/div[2]')
        Area.append(area.text)
    except NoSuchElementException:
        Area.append('Null')
    except StaleElementReferenceException:
        Area.append('Null')
    except WebDriverException:
        Area.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    try:
        price = driver.find_element(By.XPATH, '//div[@class="property-card-bottom-price"]/p')
        Price.append(price.text)
    except NoSuchElementException:
        Price.append('Null')
    except StaleElementReferenceException:
        price.append('Null')
    except WebDriverException:
        price.append('Null')  
    except TimeoutException as e:
        print('Exception Raise:', e)
    try:
        ac = driver.find_element(By.XPATH, '//*[@id="property-amenities"]/div/div/div/rb-property-rb-amenities/div/rb-amenities/ul/li[1]/div/span[2]')
        AC.append(ac.text)
    except NoSuchElementException:
        AC.append('Null')
    except WebDriverException:
        AC.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)

    try:
        dishwasher = driver.find_element(By.XPATH, '//*[@id="property-amenities"]/div/div/div/rb-property-mls-amenities/div/rb-mls-amenities/ul/li[9]/span[2]')
        Dishwasher.append(dishwasher.text)
    except NoSuchElementException:
        Dishwasher.append('Null')
    except WebDriverException:
        Dishwasher.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    except StaleElementReferenceException:
        Dishwasher.append('Null')

    
    try:
        address = driver.find_element(By.XPATH, '//span[@class="property-data-address-name"]')
        Address.append(address.text)
    except NoSuchElementException:
        Address.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    except WebDriverException:
        Address.append('Null')
    except StaleElementReferenceException:
        Address.append('Null')
        
    try:
        pets = driver.find_element(By.XPATH, '//*[@id="main-info"]/section/div/div/rb-property-facilities/section/div[4]/span[2]')
        Pets.append(pets.text)
    except NoSuchElementException:
        Pets.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    except WebDriverException:
        Pets.append('Null')
    except StaleElementReferenceException:
        Pets.append('Null')

In [11]:
DF11 = pd.DataFrame({'Address':Address,'Bed':Bed,'Bath':Bath,'Area':Area,'Pets':Pets,'Dishwasher':Dishwasher,'AC':AC,'Price':Price})
DF11

,Address,Bed,Bath,Area,Pets,Dishwasher,AC,Price
0,"Fremantle, City of Fremantle, Australia",1,1,431 \nSq Ft,No pets,Washer,Air Conditioning,"$4,116"
1,"Fremantle, City of Fremantle, Australia",3,1,Null,Null,Outdoor Space,Air Conditioning,"$6,959"
2,"Dianella WA 6059, Australia",1,1,753 \nSq Ft,No pets,Shower,Air Conditioning,"$2,150"
3,"Scarborough WA 6019, Australia",2,1,Null,Null,Hair Dryer,Air Conditioning,"$8,953"
4,"Fremantle, City of Fremantle, Australia",2,1,"1,507 \nSq Ft",No pets,Patio,Air Conditioning,"$8,232"
...,...,...,...,...,...,...,...,...
325,"Redcliffe WA 6104, Australia",2,2,Null,Null,Hair Dryer,Air Conditioning,"$5,431"
326,"Crawley WA 6009, Australia",1,Null,Null,Null,Hair Dryer,Air Conditioning,"$4,965"
327,"WA 6054, Australia",2,2,Null,Cats,Tv,Air Conditioning,"$5,813"
328,"Beckenham WA 6107, Australia",1,1,Null,Null,Bed Sheets Provided,Air Conditioning,"$4,158"
329,"Darlington, Shire Of Mundaring, Western Austra...",2,2,Null,Null,Patio,Air Conditioning,"$8,868"

In [12]:
import time
import csv
csv_file_path = 'DF11.csv'
with open(csv_file_path, 'w', newline='', encoding='utf-8') as csv_file_path:
    csv_writer = csv.writer(csv_file_path)

import joblib
joblib.dump(DF11,'df11')

New_Data_Scraped8 =  joblib.load('df11')
New_Data_Scraped8

,Address,Bed,Bath,Area,Pets,Dishwasher,AC,Price
0,"Fremantle, City of Fremantle, Australia",1,1,431 \nSq Ft,No pets,Washer,Air Conditioning,"$4,116"
1,"Fremantle, City of Fremantle, Australia",3,1,Null,Null,Outdoor Space,Air Conditioning,"$6,959"
2,"Dianella WA 6059, Australia",1,1,753 \nSq Ft,No pets,Shower,Air Conditioning,"$2,150"
3,"Scarborough WA 6019, Australia",2,1,Null,Null,Hair Dryer,Air Conditioning,"$8,953"
4,"Fremantle, City of Fremantle, Australia",2,1,"1,507 \nSq Ft",No pets,Patio,Air Conditioning,"$8,232"
...,...,...,...,...,...,...,...,...
325,"Redcliffe WA 6104, Australia",2,2,Null,Null,Hair Dryer,Air Conditioning,"$5,431"
326,"Crawley WA 6009, Australia",1,Null,Null,Null,Hair Dryer,Air Conditioning,"$4,965"
327,"WA 6054, Australia",2,2,Null,Cats,Tv,Air Conditioning,"$5,813"
328,"Beckenham WA 6107, Australia",1,1,Null,Null,Bed Sheets Provided,Air Conditioning,"$4,158"
329,"Darlington, Shire Of Mundaring, Western Austra...",2,2,Null,Null,Patio,Air Conditioning,"$8,868"

In [13]:
New_Data_Scraped8.to_excel("df11.xlsx", index = True, header = True)
print('spreadsheet saved :')

spreadsheet saved :

In [14]:
driver.close()