In [1]:
from bs4 import BeautifulSoup
import selenium
from selenium.common.exceptions import TimeoutException
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException, WebDriverException
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import requests
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
import requests

In [2]:
driver = webdriver.Chrome()

In [3]:
driver.get('https://rentberry.com/es/apartments/s/madrid-spain')
time.sleep(2)

In [4]:
consent = driver.find_element(By.XPATH, '/html/body/div[2]/div/div/div/div[2]/button[3]')
consent.click()

In [5]:
Rent_url = []
start = 0
end = 10
for page in range (start,end):
    url = driver.find_elements(By.XPATH,'//a[@class="property-card-bottom-address__text link-ghost font-xs one-line-string"]')
    for i in url:
        Rent_url.append(i.get_attribute('href'))
    
    Next_button = driver.find_elements(By.XPATH, '//span[@class="pagination-arrow-next"]')
    time.sleep(3)

In [6]:
print(len(Rent_url))

220

In [7]:
Bed = []
Bath = []
Area = []
Price = []
Pets = []
Address =[]
Deposit = []
AC  = []
Dishwasher = []
Storage = []

In [8]:
for url in Rent_url:
    driver.get(url)
    delay = 3
    
    try:
        bed = driver.find_element(By.XPATH, '//*[@id="main-info"]/rb-apartment-card-swiper/div/div[3]/rb-apartment-internals/section/div[1]/div[2]/span[1]')
        Bed.append(bed.text)
    except NoSuchElementException:
        Bed.append('Null')
    except StaleElementReferenceException:
        Bed.append('Null')
    except WebDriverException:
        Bed.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    try:
        bath = driver.find_element(By.XPATH, '//span[@class="bathrooms"]')
        Bath.append(bath.text)
    except NoSuchElementException:
        Bath.append('Null')
    except StaleElementReferenceException:
        Bath.append('Null')
    except WebDriverException:
        Bath.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    try:
        area = driver.find_element(By.XPATH, '//div[@class="internals-item"][3]/div[2]')
        Area.append(area.text)
    except NoSuchElementException:
        Area.append('Null')
    except StaleElementReferenceException:
        Area.append('Null')
    except WebDriverException:
        Area.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    try:
        price = driver.find_element(By.XPATH, '//div[@class="property-card-bottom-price"]/p')
        Price.append(price.text)
    except NoSuchElementException:
        Price.append('Null')
    except StaleElementReferenceException:
        price.append('Null')
    except WebDriverException:
        price.append('Null')  
    except TimeoutException as e:
        print('Exception Raise:', e)
    try:
        ac = driver.find_element(By.XPATH, '//*[@id="property-amenities"]/div/div/div/rb-property-rb-amenities/div/rb-amenities/ul/li[4]/div/span[2]')
        AC.append(ac.text)
    except NoSuchElementException:
        AC.append('Null')
    except WebDriverException:
        AC.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)

    try:
        dishwasher = driver.find_element(By.XPATH, '//*[@id="property-amenities"]/div/div/div/rb-property-rb-amenities/div/rb-amenities/ul/li[3]/div/span[2]')
        Dishwasher.append(dishwasher.text)
    except NoSuchElementException:
        Dishwasher.append('Null')
    except WebDriverException:
        Dishwasher.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    except StaleElementReferenceException:
        Dishwasher.append('Null')

    
    try:
        address = driver.find_element(By.XPATH, '//span[@class="property-data-address-name"]')
        Address.append(address.text)
    except NoSuchElementException:
        Address.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    except WebDriverException:
        Address.append('Null')
    except StaleElementReferenceException:
        Address.append('Null')
        
    try:
        pets = driver.find_element(By.XPATH, '//*[@id="main-info"]/section/div/div/rb-property-facilities/section/div[4]/span[2]')
        Pets.append(pets.text)
    except NoSuchElementException:
        Pets.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    except WebDriverException:
        Pets.append('Null')
    except StaleElementReferenceException:
        Pets.append('Null')

In [9]:
DF17 = pd.DataFrame({'Address':Address,'Bed':Bed,'Bath':Bath,'Area':Area,'Pets':Pets,'Dishwasher':Dishwasher,'AC':AC,'Price':Price})
DF17

,Address,Bed,Bath,Area,Pets,Dishwasher,AC,Price
0,"Rastro Market, Plaza de la Cebada, 28005 Madri...",5,1,69 \nm,Dogs,Washer/Dryer In Unit,Air Conditioning,"€2,170"
1,"Madrid, Avenida de Alfonso XIII, 83, 28016 Madrid",5,1,75 \nm,Dogs,Washer/Dryer In Unit,Air Conditioning,"€2,175"
2,"Madrid, Paseo de los Talleres, 14, 28041 Madrid",3,1,65 \nm,No pets,Washer/Dryer In Unit,Air Conditioning,"€3,604"
3,"Madrid, Calle de San Marcos, 2, 28004 Madrid",Studio,1,22 \nm,No pets,Air Conditioning,Dishwasher,"€1,650"
4,"Madrid, Iris, Calle del Conde de Romanones, 28...",3,2,80 \nm,Dogs,Air Conditioning,Utilities Included,"€1,955"
...,...,...,...,...,...,...,...,...
215,"Madrid, Calle de Santa Brígida, 23, 28004 Madrid",1,1,55 \nm,No pets,Utilities Included,Elevator,"€3,400"
216,"Madrid, Calle de Beatriz Galindo, 8, 28521 Riv...",Studio,1,25 \nm,Null,Null,Null,€818
217,"La Casita, Calle de Sánchez Preciado, 38, 2803...",3,2,82 \nm,No pets,Washer/Dryer In Unit,Air Conditioning,"€2,550"
218,Null,Null,Null,Null,Null,Null,Null,Null
219,Null,Null,Null,Null,Null,Null,Null,Null

In [10]:
import time
import csv
csv_file_path = 'DF17.csv'
with open(csv_file_path, 'w', newline='', encoding='utf-8') as csv_file_path:
    csv_writer = csv.writer(csv_file_path)

import joblib
joblib.dump(DF17,'df17')

New_Data_Scraped14 =  joblib.load('df17')
New_Data_Scraped14

,Address,Bed,Bath,Area,Pets,Dishwasher,AC,Price
0,"Rastro Market, Plaza de la Cebada, 28005 Madri...",5,1,69 \nm,Dogs,Washer/Dryer In Unit,Air Conditioning,"€2,170"
1,"Madrid, Avenida de Alfonso XIII, 83, 28016 Madrid",5,1,75 \nm,Dogs,Washer/Dryer In Unit,Air Conditioning,"€2,175"
2,"Madrid, Paseo de los Talleres, 14, 28041 Madrid",3,1,65 \nm,No pets,Washer/Dryer In Unit,Air Conditioning,"€3,604"
3,"Madrid, Calle de San Marcos, 2, 28004 Madrid",Studio,1,22 \nm,No pets,Air Conditioning,Dishwasher,"€1,650"
4,"Madrid, Iris, Calle del Conde de Romanones, 28...",3,2,80 \nm,Dogs,Air Conditioning,Utilities Included,"€1,955"
...,...,...,...,...,...,...,...,...
215,"Madrid, Calle de Santa Brígida, 23, 28004 Madrid",1,1,55 \nm,No pets,Utilities Included,Elevator,"€3,400"
216,"Madrid, Calle de Beatriz Galindo, 8, 28521 Riv...",Studio,1,25 \nm,Null,Null,Null,€818
217,"La Casita, Calle de Sánchez Preciado, 38, 2803...",3,2,82 \nm,No pets,Washer/Dryer In Unit,Air Conditioning,"€2,550"
218,Null,Null,Null,Null,Null,Null,Null,Null
219,Null,Null,Null,Null,Null,Null,Null,Null

In [11]:
New_Data_Scraped14.to_excel("df17.xlsx", index = True, header = True)
print('spreadsheet saved :')

spreadsheet saved :