In [1]:
from bs4 import BeautifulSoup
import selenium
from selenium.common.exceptions import TimeoutException
import pandas as pd
from selenium import webdriver
import time
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException, WebDriverException
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import requests
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
import requests

In [2]:
driver = webdriver.Chrome()

In [3]:
driver.get('https://rentberry.com/jp/apartments/s/tokyo-japan')
time.sleep(2)

In [4]:
consent = driver.find_element(By.XPATH, '/html/body/div[2]/div/div/div/div[2]/button[3]')
consent.click()

In [5]:
Rent_url = []
start = 0
end = 15
for page in range (start,end):
    url = driver.find_elements(By.XPATH,'//a[@class="property-card-bottom-address__text link-ghost font-xs one-line-string"]')
    for i in url:
        Rent_url.append(i.get_attribute('href'))
    
    Next_button = driver.find_elements(By.XPATH, '//span[@class="pagination-arrow-next"]')
    time.sleep(3)

In [6]:
print(len(Rent_url))

330

In [7]:
Bed = []
Bath = []
Area = []
Price = []
Pets = []
Address =[]
Deposit = []
AC  = []
Dishwasher = []
Storage = []

In [8]:
for url in Rent_url:
    driver.get(url)
    delay = 3
    
    try:
        bed = driver.find_element(By.XPATH, '//*[@id="main-info"]/rb-apartment-card-swiper/div/div[3]/rb-apartment-internals/section/div[1]/div[2]/span[1]')
        Bed.append(bed.text)
    except NoSuchElementException:
        Bed.append('Null')
    except StaleElementReferenceException:
        Bed.append('Null')
    except WebDriverException:
        Bed.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    try:
        bath = driver.find_element(By.XPATH, '//span[@class="bathrooms"]')
        Bath.append(bath.text)
    except NoSuchElementException:
        Bath.append('Null')
    except StaleElementReferenceException:
        Bath.append('Null')
    except WebDriverException:
        Bath.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    try:
        area = driver.find_element(By.XPATH, '//div[@class="internals-item"][3]/div[2]')
        Area.append(area.text)
    except NoSuchElementException:
        Area.append('Null')
    except StaleElementReferenceException:
        Area.append('Null')
    except WebDriverException:
        Area.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    try:
        price = driver.find_element(By.XPATH, '//div[@class="property-card-bottom-price"]/p')
        Price.append(price.text)
    except NoSuchElementException:
        Price.append('Null')
    except StaleElementReferenceException:
        price.append('Null')
    except WebDriverException:
        price.append('Null')  
    except TimeoutException as e:
        print('Exception Raise:', e)
    try:
        ac = driver.find_element(By.XPATH, '//*[@id="property-amenities"]/div/div/div/rb-property-rb-amenities/div/rb-amenities/ul/li/div/span[2]')
        AC.append(ac.text)
    except NoSuchElementException:
        AC.append('Null')
    except WebDriverException:
        AC.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)

    try:
        dishwasher = driver.find_element(By.XPATH, '//*[@id="property-amenities"]/div/div/div/rb-property-mls-amenities/div/rb-mls-amenities/ul/li[7]/span[2]')
        Dishwasher.append(dishwasher.text)
    except NoSuchElementException:
        Dishwasher.append('Null')
    except WebDriverException:
        Dishwasher.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    except StaleElementReferenceException:
        Dishwasher.append('Null')

    
    try:
        address = driver.find_element(By.XPATH, '//span[@class="property-data-address-name"]')
        Address.append(address.text)
    except NoSuchElementException:
        Address.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    except WebDriverException:
        Address.append('Null')
    except StaleElementReferenceException:
        Address.append('Null')
        
    try:
        pets = driver.find_element(By.XPATH, '//*[@id="main-info"]/section/div/div/rb-property-facilities/section/div[4]/span[2]')
        Pets.append(pets.text)
    except NoSuchElementException:
        Pets.append('Null')
    except TimeoutException as e:
        print('Exception Raise:', e)
    except WebDriverException:
        Pets.append('Null')
    except StaleElementReferenceException:
        Pets.append('Null')

In [9]:
DF8 = pd.DataFrame({'Address':Address,'Bed':Bed,'Bath':Bath,'Area':Area,'Pets':Pets,'Dishwasher':Dishwasher,'AC':AC,'Price':Price})
DF8

,Address,Bed,Bath,Area,Pets,Dishwasher,AC,Price
0,"Kamakura, Kanagawa Prefecture, Japan",2,1,807 \nSq Ft,No pets,Washer,Air Conditioning,"¥616,891"
1,"Minato, Japan",1,1,560 \nSq Ft,No pets,Tv,Air Conditioning,"¥1,78M"
2,"Shinjuku, 160-0022, Japan",2,1,431 \nSq Ft,No pets,Tv,Air Conditioning,"¥887,033"
3,"Setagaya, Japan",1,1,312 \nSq Ft,No pets,Tv,Air Conditioning,"¥499,964"
4,"Suginami, Japan",Studio,Null,Null,Null,Hair Dryer,Air Conditioning,"¥399,165"
...,...,...,...,...,...,...,...,...
325,"Kōdō, Adachi, 120-0013, Japan",Studio,Null,Null,Null,Tv,Air Conditioning,"¥249,982"
326,"Arakawa, Japan",1,1,172 \nSq Ft,No pets,Washer,Null,"¥342,717"
327,"Kōdō, Adachi, 120-0013, Japan",Studio,Null,Null,Null,Washing Machine,Air Conditioning,"¥298,366"
328,"Chuo, Japan",1,1,205 \nSq Ft,No pets,Towels Provided,Air Conditioning,"¥689,467"
329,"Minato, Japan",1,1,538 \nSq Ft,Dogs,Tv,Air Conditioning,Null

In [10]:
import time
import csv

In [11]:
csv_file_path = 'DF8.csv'
with open(csv_file_path, 'w', newline='', encoding='utf-8') as csv_file_path:
    csv_writer = csv.writer(csv_file_path)

In [12]:
import joblib
joblib.dump(DF8,'df8')

['df8']

In [13]:
New_Data_Scraped5 =  joblib.load('df8')
New_Data_Scraped5

,Address,Bed,Bath,Area,Pets,Dishwasher,AC,Price
0,"Kamakura, Kanagawa Prefecture, Japan",2,1,807 \nSq Ft,No pets,Washer,Air Conditioning,"¥616,891"
1,"Minato, Japan",1,1,560 \nSq Ft,No pets,Tv,Air Conditioning,"¥1,78M"
2,"Shinjuku, 160-0022, Japan",2,1,431 \nSq Ft,No pets,Tv,Air Conditioning,"¥887,033"
3,"Setagaya, Japan",1,1,312 \nSq Ft,No pets,Tv,Air Conditioning,"¥499,964"
4,"Suginami, Japan",Studio,Null,Null,Null,Hair Dryer,Air Conditioning,"¥399,165"
...,...,...,...,...,...,...,...,...
325,"Kōdō, Adachi, 120-0013, Japan",Studio,Null,Null,Null,Tv,Air Conditioning,"¥249,982"
326,"Arakawa, Japan",1,1,172 \nSq Ft,No pets,Washer,Null,"¥342,717"
327,"Kōdō, Adachi, 120-0013, Japan",Studio,Null,Null,Null,Washing Machine,Air Conditioning,"¥298,366"
328,"Chuo, Japan",1,1,205 \nSq Ft,No pets,Towels Provided,Air Conditioning,"¥689,467"
329,"Minato, Japan",1,1,538 \nSq Ft,Dogs,Tv,Air Conditioning,Null

In [15]:
New_Data_Scraped5.to_excel("df8.xlsx", index = True, header = True)
print('spreadsheet saved :')

spreadsheet saved :

In [16]:
driver.close()